### ISSUE TITLE
Problems with numpy1.13.3

### ISSUE THREAD

**Issue by ipeikon** [velocyto-team/velocyto.py#12]
In vlm.default_fit_preparation(), numpy1.13 gives the following error:
I'm fairly sure a workaround is to intsall numpy1.11

```
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <built-in method query of sklearn.neighbors.kd_tree.KDTree object>
        args = (array([[ -2.5302447 ,  -3.73565713,   4.00488269...0.42542586,
          1.07867484,   2.27431581]]), 1281.0, True)
        kwargs = {}
    132 
    133     def __len__(self):
    134         return self._size
    135 

```
...........................................................................
/home/seqteam/programs/miniconda3/lib/python3.6/site-packages/sklearn/neighbors/kd_tree.cpython-36m-x86_64-linux-gnu.so in sklearn.neighbors.kd_tree.BinaryTree.query()

...........................................................................
/home/seqteam/programs/miniconda3/lib/python3.6/site-packages/sklearn/neighbors/kd_tree.cpython-36m-x86_64-linux-gnu.so in sklearn.neighbors.kd_tree.NeighborsHeap.__init__()

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by ipeikon** [comment]
`conda install numpy=1.11.2
`Worked for me.

**Comment by gioelelm** [comment]
I think this was fixed in latest update. Are you running the last commit?

**Comment by gioelelm** [comment]
I won't suggest your fix, I don't support older versions of numpy.
I can patch the problem if it is not already fixed by the latest commit.

**Comment by ipeikon** [comment]
I pulled the latest from git and reinstalled but still seem to be getting this issue.

**Comment by gioelelm** [comment]
Ok I will look into it to fix it, then.

**Comment by gioelelm** [comment]
What's about now? Unfortunately, I can't test this directly right now but I think I figured and fixed the problem. Could you check?

**Comment by ipeikon** [comment]
Still not working for me. But maybe when I run pip install -e . it is not putting velocyto in the right place and so I'm not actually functionally updating it?

**Comment by gioelelm** [comment]
try again git pull, you might have been a bit too quick, I had to pull the fix, it was on another branch

**Comment by ipeikon** [comment]
Ok, trying the new update. Seems to work now. Thanks for the really quick fix!

**Comment by gioelelm** [comment]
You are welcome, I care about having all the pipeline working. Sorry for this bug but the default_* functions are a new feature and they haven't been super well tested yet, like in this case.
